### ISSUE TITLE
Request to release jenkins-client v0.0.5

### ISSUE THREAD

**Issue by JohnNiang** [jenkins-zh/jenkins-client#37]
Consider `jenkins-client` is stable for now, and is suitable to be released [v0.0.5](https://github.com/jenkins-zh/jenkins-client/releases/tag/untagged-9a19b2fd1680bbf05b03).

hi @LinuxSuRen , please help us release it.

**Comment by LinuxSuRen** [comment]
Thanks for your contributions. There are 8 contributions from @JohnNiang . That is awesome!!!
