### ISSUE TITLE
Request support Blue Ocean API download artifact 

### ISSUE THREAD

**Issue by mzmuer** [jenkins-zh/jenkins-client#44]
Currently, the Blue API only supports getting a list of artifacts: 
https://github.com/jenkins-zh/jenkins-client/blob/94e2330ce3cc7303ebca41bc0de544d2c33089d5/pkg/artifact/artifacts.go

Hope to support artifact download

**Comment by mzmuer** [comment]
> IMO, you would get the artifact URL and downloaded by your self instead of Jenkins Client.
I see, that's exactly what I'm doing. Thank you.

**Comment by JohnNiang** [comment]
I'm sorry. I didn't consider the permission of that API, so I would reopen this issue later. 

It's reasonable and suitable to support artifact download via Jenkins Client. But we need to support two method to download artifact:

1. Download artifact with its name and job names
2. Download artifact with its URL
