### ISSUE TITLE
Wrong type in DurationInMillis

### ISSUE THREAD

**Issue by chengleqi** [jenkins-zh/jenkins-client#61]
The type of `DurationInMillis` in Node struct should also be `int64` as in the Step struct.
https://github.com/jenkins-zh/jenkins-client/blob/0c9041a612a1bc6047236fc1e3194fc01e33830e/pkg/job/blueocean_type.go#L131

See also:
[BluePipelineNode extends BluePipelineSteps](https://github.com/jenkinsci/blueocean-plugin/blob/6b27be3724c892427b732f30575fdcc2977cfaef/blueocean-rest/src/main/java/io/jenkins/blueocean/rest/model/BluePipelineNode.java#L63) and the type of durationInMillis in BulePipelineStep is `long`.

**Comment by LinuxSuRen** [comment]
hi @chengleqi , fair enough. Thanks for finding it. Please feel free to fix it.
